package com.maktab.app.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable

// ─────────────────────────────────────────────
// String modeli
// ─────────────────────────────────────────────
data class Strings(
    // Auth
    val appName: String,
    val loginTitle: String,
    val loginSubtitle: String,
    val loginUsername: String,
    val loginUsernameHint: String,
    val loginPassword: String,
    val loginButton: String,
    val loginLoading: String,
    val forgotPin: String,
    // Common
    val save: String,
    val cancel: String,
    val retry: String,
    val search: String,
    val addNew: String,
    val loading: String,
    val dataNotLoaded: String,
    val today: String,
    val total: String,
    val status: String,
    val active: String,
    val inactive: String,
    val pending: String,
    val send: String,
    val submit: String,
    val confirm: String,
    val reject: String,
    val correct: String,
    val mark: String,
    val days: String,
    val ball: String,
    val max: String,
    val avgScore: String,
    val date: String,
    val type: String,
    val category: String,
    val amount: String,
    val unit: String,
    val section: String,
    val start: String,
    val end: String,
    val readMore: String,
    val file: String,
    val uploadFile: String,
    val savedOk: String,
    val again: String,
    val bonus: String,
    val positionLabel: String,
    val personalInfo: String,
    val security: String,
    val settings: String,
    val last7Days: String,
    // Exit
    val exitTitle: String,
    val exitMsg: String,
    val exitYes: String,
    val logout: String,
    // Password
    val changePassword: String,
    val savePassword: String,
    val passwordChanged: String,
    val passwordHint: String,
    val passwordStrongHint: String,
    // Attendance
    val attendanceRate: String,
    val attendanceLoading: String,
    val viewAttendance: String,
    val noAttendanceWeek: String,
    val weeklyAttendanceStats: String,
    // Grades
    val noGrades: String,
    val viewGrades: String,
    val gradesBySubject: String,
    val classRanking: String,
    // Homework
    val noHomework: String,
    val recentHomework: String,
    val submitAnswer: String,
    val answerAccepted: String,
    // Exams
    val noExams: String,
    val recentExams: String,
    // Payments
    val viewPayments: String,
    val allPayments: String,
    val activeContract: String,
    val nextPaymentDate: String,
    val noPayments: String,
    val paid: String,
    // Parent
    val linkedChildren: String,
    val parentRole: String,
    val schoolParent: String,
    val studentRole: String,
    // Profile
    val profileTitle: String,
    // Complaints
    val myComplaints: String,
    val newComplaint: String,
    val complaintType: String,
    val complaintDetailHint: String,
    val complaintAccepted: String,
    val complaintReplyTime: String,
    // Surveys
    val surveysTitle: String,
    // News
    val newsComingSoon: String,
    // Teacher
    val noClassToday: String,
    val noClassAssigned: String,
    val classesLoading: String,
    val newSubject: String,
    // Chef
    val chefRole: String,
    val lowStockAlerts: String,
    val warehouseUsage: String,
    val mostUsedIngredients: String,
    val spendTrend: String,
    val recentMovements: String,
    val ingredient: String,
    val ingredientCatalog: String,
    val ingredientSearchHint: String,
    val noIngredients: String,
    val addIngredient: String,
    val newIngredient: String,
    val editIngredient: String,
    val minStock: String,
    val remaining: String,
    val movementsSearchHint: String,
    val movementsTitle: String,
    val noMovements: String,
    val menuCalendar: String,
    val noMenuToday: String,
    val selectMeal: String,
    val recipesTitle: String,
    val recipeSearchHint: String,
    val noRecipes: String,
    val newRecipe: String,
    val portion: String,
    // HR
    val employee: String,
    val employeeSearchHint: String,
    val noEmployee: String,
    val addEmployee: String,
    val employeeAdded: String,
    val departmentsByEmployees: String,
    val salaryDistribution: String,
    val documentsTitle: String,
    val documentSearchHint: String,
    // Behavior
    val noBehaviorRecords: String,
)

// ─────────────────────────────────────────────
// O'zbek (default)
// ─────────────────────────────────────────────
val UzStrings = Strings(
    appName = "Maktab",
    loginTitle = "Maktab tizimi",
    loginSubtitle = "Hisobingizga kiring",
    loginUsername = "Foydalanuvchi nomi",
    loginUsernameHint = "username",
    loginPassword = "Parol",
    loginButton = "Kirish",
    loginLoading = "Kirilmoqda…",
    forgotPin = "PIN kodni unutdim",
    save = "Saqlash",
    cancel = "Bekor qilish",
    retry = "Qayta urinish",
    search = "Qidirish",
    addNew = "Yangi",
    loading = "Yuklanmoqda…",
    dataNotLoaded = "Ma'lumot yuklanmadi",
    today = "Bugun",
    total = "Jami",
    status = "Holat",
    active = "Faol",
    inactive = "Nofaol",
    pending = "Kutilmoqda",
    send = "Yuborish",
    submit = "Topshirish",
    confirm = "Tasdiqlash",
    reject = "Rad etish",
    correct = "To'g'ri",
    mark = "Belgilash",
    days = "Kunlar",
    ball = "Ball",
    max = "Maksimal",
    avgScore = "O'rtacha ball",
    date = "Sana",
    type = "Tur",
    category = "Kategoriya",
    amount = "Miqdor",
    unit = "O'lchov birligi",
    section = "Bo'lim",
    start = "Boshlanish",
    end = "Tugash",
    readMore = "Batafsil o'qish",
    file = "Fayl",
    uploadFile = "Fayl yuklash",
    savedOk = "Muvaffaqiyatli saqlandi!",
    again = "Qayta",
    bonus = "Bonus",
    positionLabel = "LAVOZIM",
    personalInfo = "SHAXSIY MA'LUMOTLAR",
    security = "XAVFSIZLIK",
    settings = "Sozlamalar",
    last7Days = "Oxirgi 7 kun",
    exitTitle = "Ilovadan chiqasizmi?",
    exitMsg = "Ilovani yopmoqchimisiz? Keyingi kirishda PIN kod so'raladi.",
    exitYes = "Ha, chiqish",
    logout = "Chiqish",
    changePassword = "Parolni almashtirish",
    savePassword = "Parolni saqlash",
    passwordChanged = "Parol muvaffaqiyatli o'zgartirildi!",
    passwordHint = "Kabinet parolini vaqt-vaqti bilan yangilab turing.",
    passwordStrongHint = "Kuchli parol uchun harflar, raqamlar va maxsus belgilardan foydalaning.",
    attendanceRate = "Davomat foizi",
    attendanceLoading = "Davomat yuklanmoqda…",
    viewAttendance = "Davomatni ko'rish",
    noAttendanceWeek = "Bu hafta davomat yozuvi yo'q",
    weeklyAttendanceStats = "Haftalik davomat statistikasi",
    noGrades = "Baholar hali kiritilmagan",
    viewGrades = "Baholarni ko'rish",
    gradesBySubject = "Fan bo'yicha baholar",
    classRanking = "Sinf reytingi",
    noHomework = "Uyga vazifalar hali berilmagan",
    recentHomework = "So'nggi vazifalar",
    submitAnswer = "Javob yuborish",
    answerAccepted = "Javobingiz qabul qilindi",
    noExams = "Imtihon natijalari hali yo'q",
    recentExams = "So'nggi imtihonlar",
    viewPayments = "To'lovlarni ko'rish",
    allPayments = "Barcha to'lovlar",
    activeContract = "Faol shartnoma",
    nextPaymentDate = "Keyingi to'lov sanasi",
    noPayments = "Shartnoma va to'lovlar hali yo'q",
    paid = "To'landi",
    linkedChildren = "BOG'LANGAN FARZANDLAR",
    parentRole = "Ota-ona",
    schoolParent = "Maktab ota-onasi",
    studentRole = "O'quvchi",
    profileTitle = "Profil",
    myComplaints = "Mening murojaatlarim",
    newComplaint = "Yangi murojaat",
    complaintType = "Murojaat turi",
    complaintDetailHint = "Muammoni batafsil yozing…",
    complaintAccepted = "Murojaatingiz qabul qilindi",
    complaintReplyTime = "Maktab ma'muriyati 2 ish kuni ichida ko'rib chiqadi",
    surveysTitle = "So'rovlar",
    newsComingSoon = "Yangiliklar tez orada",
    noClassToday = "Bu kun dars yo'q",
    noClassAssigned = "Backend da o'qituvchiga sinf biriktirilmagan",
    classesLoading = "Sinflar yuklanmoqda…",
    newSubject = "Yangi fan",
    chefRole = "Oshpaz · Kafeteriya",
    lowStockAlerts = "Ombor ogohlantirishlari",
    warehouseUsage = "Ombor ishlatilishi",
    mostUsedIngredients = "Eng ko'p ishlatilgan ingredientlar",
    spendTrend = "Sarf trendi",
    recentMovements = "So'nggi ombor harakatlari",
    ingredient = "Ingredient",
    ingredientCatalog = "Ingredient katalogi",
    ingredientSearchHint = "Ingredient yoki kategoriya qidirish",
    noIngredients = "Ingredientlar topilmadi",
    addIngredient = "Yangi ingredient qo'shish",
    newIngredient = "Yangi ingredient",
    editIngredient = "Ingredientni tahrirlash",
    minStock = "Min.qoldiq",
    remaining = "Qoldiq",
    movementsSearchHint = "Harakat, sabab yoki ingredient qidirish",
    movementsTitle = "Harakatlar",
    noMovements = "Harakatlar topilmadi",
    menuCalendar = "Menyu kalendari",
    noMenuToday = "Bu kun uchun taom belgilanmagan",
    selectMeal = "Taom tanlang",
    recipesTitle = "Retseptlar",
    recipeSearchHint = "Retsept qidirish",
    noRecipes = "Retseptlar topilmadi",
    newRecipe = "Yangi retsept",
    portion = "Porsiya",
    employee = "Xodim",
    employeeSearchHint = "Xodim qidirish…",
    noEmployee = "Xodim topilmadi",
    addEmployee = "Xodimni qo'shish",
    employeeAdded = "Xodim muvaffaqiyatli qo'shildi!",
    departmentsByEmployees = "Bo'limlar bo'yicha xodimlar",
    salaryDistribution = "Maosh taqsimoti",
    documentsTitle = "Hujjatlar",
    documentSearchHint = "Hujjat qidirish…",
    noBehaviorRecords = "Xulq yozuvlari hali yo'q",
)

// ─────────────────────────────────────────────
// Rus tili
// ─────────────────────────────────────────────
val RuStrings = Strings(
    appName = "Мактаб",
    loginTitle = "Система Мактаб",
    loginSubtitle = "Войдите в свой аккаунт",
    loginUsername = "Имя пользователя",
    loginUsernameHint = "username",
    loginPassword = "Пароль",
    loginButton = "Войти",
    loginLoading = "Вход…",
    forgotPin = "Забыл PIN-код",
    save = "Сохранить",
    cancel = "Отмена",
    retry = "Повторить",
    search = "Поиск",
    addNew = "Новый",
    loading = "Загрузка…",
    dataNotLoaded = "Данные не загружены",
    today = "Сегодня",
    total = "Всего",
    status = "Статус",
    active = "Активный",
    inactive = "Неактивный",
    pending = "В ожидании",
    send = "Отправить",
    submit = "Сдать",
    confirm = "Подтвердить",
    reject = "Отклонить",
    correct = "Верно",
    mark = "Отметить",
    days = "Дни",
    ball = "Балл",
    max = "Максимум",
    avgScore = "Средний балл",
    date = "Дата",
    type = "Тип",
    category = "Категория",
    amount = "Количество",
    unit = "Единица измерения",
    section = "Раздел",
    start = "Начало",
    end = "Конец",
    readMore = "Читать далее",
    file = "Файл",
    uploadFile = "Загрузить файл",
    savedOk = "Успешно сохранено!",
    again = "Снова",
    bonus = "Бонус",
    positionLabel = "ДОЛЖНОСТЬ",
    personalInfo = "ЛИЧНЫЕ ДАННЫЕ",
    security = "БЕЗОПАСНОСТЬ",
    settings = "Настройки",
    last7Days = "Последние 7 дней",
    exitTitle = "Выйти из приложения?",
    exitMsg = "Вы хотите закрыть приложение? При следующем входе потребуется PIN-код.",
    exitYes = "Да, выйти",
    logout = "Выйти",
    changePassword = "Изменить пароль",
    savePassword = "Сохранить пароль",
    passwordChanged = "Пароль успешно изменён!",
    passwordHint = "Периодически обновляйте пароль кабинета.",
    passwordStrongHint = "Используйте буквы, цифры и специальные символы для надёжного пароля.",
    attendanceRate = "Процент посещаемости",
    attendanceLoading = "Загрузка посещаемости…",
    viewAttendance = "Посещаемость",
    noAttendanceWeek = "На этой неделе нет записей",
    weeklyAttendanceStats = "Еженедельная статистика",
    noGrades = "Оценки ещё не выставлены",
    viewGrades = "Оценки",
    gradesBySubject = "Оценки по предметам",
    classRanking = "Рейтинг класса",
    noHomework = "Домашние задания ещё не заданы",
    recentHomework = "Последние задания",
    submitAnswer = "Отправить ответ",
    answerAccepted = "Ваш ответ принят",
    noExams = "Результаты экзаменов отсутствуют",
    recentExams = "Последние экзамены",
    viewPayments = "Платежи",
    allPayments = "Все платежи",
    activeContract = "Активный договор",
    nextPaymentDate = "Следующая дата оплаты",
    noPayments = "Договоры и платежи отсутствуют",
    paid = "Оплачено",
    linkedChildren = "ПРИВЯЗАННЫЕ ДЕТИ",
    parentRole = "Родитель",
    schoolParent = "Родитель школы",
    studentRole = "Ученик",
    profileTitle = "Профиль",
    myComplaints = "Мои обращения",
    newComplaint = "Новое обращение",
    complaintType = "Тип обращения",
    complaintDetailHint = "Опишите проблему подробнее…",
    complaintAccepted = "Ваше обращение принято",
    complaintReplyTime = "Администрация рассмотрит в течение 2 рабочих дней",
    surveysTitle = "Опросы",
    newsComingSoon = "Новости скоро появятся",
    noClassToday = "Сегодня нет занятий",
    noClassAssigned = "Учителю не назначен класс",
    classesLoading = "Загрузка классов…",
    newSubject = "Новый предмет",
    chefRole = "Повар · Кафетерий",
    lowStockAlerts = "Уведомления склада",
    warehouseUsage = "Использование склада",
    mostUsedIngredients = "Часто используемые ингредиенты",
    spendTrend = "Тренд расходов",
    recentMovements = "Последние движения склада",
    ingredient = "Ингредиент",
    ingredientCatalog = "Каталог ингредиентов",
    ingredientSearchHint = "Поиск по ингредиенту или категории",
    noIngredients = "Ингредиенты не найдены",
    addIngredient = "Добавить ингредиент",
    newIngredient = "Новый ингредиент",
    editIngredient = "Редактировать ингредиент",
    minStock = "Мин.остаток",
    remaining = "Остаток",
    movementsSearchHint = "Поиск по движению, причине или ингредиенту",
    movementsTitle = "Движения",
    noMovements = "Движения не найдены",
    menuCalendar = "Меню-календарь",
    noMenuToday = "Меню на сегодня не назначено",
    selectMeal = "Выбрать блюдо",
    recipesTitle = "Рецепты",
    recipeSearchHint = "Поиск рецептов",
    noRecipes = "Рецепты не найдены",
    newRecipe = "Новый рецепт",
    portion = "Порция",
    employee = "Сотрудник",
    employeeSearchHint = "Поиск сотрудника…",
    noEmployee = "Сотрудник не найден",
    addEmployee = "Добавить сотрудника",
    employeeAdded = "Сотрудник успешно добавлен!",
    departmentsByEmployees = "Сотрудники по отделам",
    salaryDistribution = "Распределение зарплат",
    documentsTitle = "Документы",
    documentSearchHint = "Поиск документов…",
    noBehaviorRecords = "Записей о поведении нет",
)

// ─────────────────────────────────────────────
// Ingliz tili
// ─────────────────────────────────────────────
val EnStrings = Strings(
    appName = "Maktab",
    loginTitle = "Maktab System",
    loginSubtitle = "Sign in to your account",
    loginUsername = "Username",
    loginUsernameHint = "username",
    loginPassword = "Password",
    loginButton = "Sign In",
    loginLoading = "Signing in…",
    forgotPin = "Forgot PIN",
    save = "Save",
    cancel = "Cancel",
    retry = "Retry",
    search = "Search",
    addNew = "New",
    loading = "Loading…",
    dataNotLoaded = "Data not loaded",
    today = "Today",
    total = "Total",
    status = "Status",
    active = "Active",
    inactive = "Inactive",
    pending = "Pending",
    send = "Send",
    submit = "Submit",
    confirm = "Confirm",
    reject = "Reject",
    correct = "Correct",
    mark = "Mark",
    days = "Days",
    ball = "Score",
    max = "Maximum",
    avgScore = "Average score",
    date = "Date",
    type = "Type",
    category = "Category",
    amount = "Quantity",
    unit = "Unit",
    section = "Section",
    start = "Start",
    end = "End",
    readMore = "Read more",
    file = "File",
    uploadFile = "Upload file",
    savedOk = "Saved successfully!",
    again = "Again",
    bonus = "Bonus",
    positionLabel = "POSITION",
    personalInfo = "PERSONAL INFO",
    security = "SECURITY",
    settings = "Settings",
    last7Days = "Last 7 days",
    exitTitle = "Exit app?",
    exitMsg = "Do you want to close the app? PIN will be required next time.",
    exitYes = "Yes, exit",
    logout = "Sign out",
    changePassword = "Change password",
    savePassword = "Save password",
    passwordChanged = "Password changed successfully!",
    passwordHint = "Update your password regularly.",
    passwordStrongHint = "Use letters, numbers and special characters for a strong password.",
    attendanceRate = "Attendance rate",
    attendanceLoading = "Loading attendance…",
    viewAttendance = "View attendance",
    noAttendanceWeek = "No attendance records this week",
    weeklyAttendanceStats = "Weekly attendance stats",
    noGrades = "No grades entered yet",
    viewGrades = "View grades",
    gradesBySubject = "Grades by subject",
    classRanking = "Class ranking",
    noHomework = "No homework assigned yet",
    recentHomework = "Recent homework",
    submitAnswer = "Submit answer",
    answerAccepted = "Your answer was accepted",
    noExams = "No exam results yet",
    recentExams = "Recent exams",
    viewPayments = "View payments",
    allPayments = "All payments",
    activeContract = "Active contract",
    nextPaymentDate = "Next payment date",
    noPayments = "No contracts or payments yet",
    paid = "Paid",
    linkedChildren = "LINKED CHILDREN",
    parentRole = "Parent",
    schoolParent = "School parent",
    studentRole = "Student",
    profileTitle = "Profile",
    myComplaints = "My complaints",
    newComplaint = "New complaint",
    complaintType = "Complaint type",
    complaintDetailHint = "Describe the problem in detail…",
    complaintAccepted = "Your complaint has been received",
    complaintReplyTime = "Administration will review within 2 working days",
    surveysTitle = "Surveys",
    newsComingSoon = "News coming soon",
    noClassToday = "No classes today",
    noClassAssigned = "No class assigned to teacher",
    classesLoading = "Loading classes…",
    newSubject = "New subject",
    chefRole = "Chef · Cafeteria",
    lowStockAlerts = "Low stock alerts",
    warehouseUsage = "Warehouse usage",
    mostUsedIngredients = "Most used ingredients",
    spendTrend = "Spend trend",
    recentMovements = "Recent warehouse movements",
    ingredient = "Ingredient",
    ingredientCatalog = "Ingredient catalog",
    ingredientSearchHint = "Search ingredient or category",
    noIngredients = "No ingredients found",
    addIngredient = "Add ingredient",
    newIngredient = "New ingredient",
    editIngredient = "Edit ingredient",
    minStock = "Min.stock",
    remaining = "Remaining",
    movementsSearchHint = "Search by movement, reason or ingredient",
    movementsTitle = "Movements",
    noMovements = "No movements found",
    menuCalendar = "Menu calendar",
    noMenuToday = "No menu set for today",
    selectMeal = "Select meal",
    recipesTitle = "Recipes",
    recipeSearchHint = "Search recipes",
    noRecipes = "No recipes found",
    newRecipe = "New recipe",
    portion = "Portion",
    employee = "Employee",
    employeeSearchHint = "Search employee…",
    noEmployee = "Employee not found",
    addEmployee = "Add employee",
    employeeAdded = "Employee added successfully!",
    departmentsByEmployees = "Employees by department",
    salaryDistribution = "Salary distribution",
    documentsTitle = "Documents",
    documentSearchHint = "Search documents…",
    noBehaviorRecords = "No behavior records",
)

// ─────────────────────────────────────────────
// Compose accessor
// ─────────────────────────────────────────────
val str: Strings
    @Composable
    @ReadOnlyComposable
    get() = when (LocalAppLang.current) {
        "ru" -> RuStrings
        "en" -> EnStrings
        else -> UzStrings
    }